Blog_MVC/Blog_MVC/Controllers/EtiketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog_MVC.Controllers
{
    using Models;
    public class EtiketController : Controller
    {
        SugarBlogContext context = new SugarBlogContext();
        // GET: Etiket
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult EtiketWidget() {

            return PartialView(context.Etikets.ToList());
        }
    }
}

Blog_MVC/Blog_MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog_MVC.Controllers
{
    using Models;
    using App_Classes;
    public class HomeController : Controller
    {
        SugarBlogContext context = new SugarBlogContext();
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult MakaleListeleWidget()
        {
            return PartialView(context.Makales.ToList());
        }

        public PartialViewResult PopulerMakalelerWidget() {
            var model = context.Makales.OrderByDescending(x => x.EklenmeTarihi).Take(3).ToList();
            return PartialView(model);
        }
    }
}

Blog_MVC/Blog_MVC/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog_MVC.Controllers
{
    using Models;
    public class KategoriController : Controller
    {
        SugarBlogContext context = new SugarBlogContext();
        // GET: Kategori
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult KategoriWidget() {

            return PartialView(context.Kategoris.ToList());
        }
    }
}

Blog_MVC/Blog_MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Ana Sayfa";
}

@{
    Html.RenderAction("MakaleListeleWidget");
}

@section Kategoriler
 {
    @{
        Html.RenderAction("KategoriWidget", "Kategori");
    }
}

@section Etiketler
 {
    @{
        Html.RenderAction("EtiketWidget", "Etiket");
    }
}

@section Arama
 {

    <div class="sidebox widget">
        <h3 class="widget-title section-title">ARA</h3>
        <form class="searchform" method="get">
            <label><i class="icon-search"></i></label>
            <input type="text" id="s2" name="s" value="Birşeyler Ara" onfocus="this.value = ''" onblur=" this.value='Birşeyler Ara' " />
            <button type="submit" class="btn">Ara</button>
        </form>
    </div>

}

@section SiteHakkinda{
    @{
        Html.RenderPartial("SiteHakkinda");

    }
}

@section PopulerMakaleler{

    @{
        Html.RenderAction("PopulerMakalelerWidget");

    }
}

Blog_MVC/Blog_MVC/Views/Home/MakaleListeleWidget.cshtml
@model IEnumerable<Blog_MVC.Models.Makale>
@helper IcerikKisalt(string metin)
{
if (metin.Length > 300)
{
        @metin.Substring(0, 300)
}
else
{
        @metin
}
}
<div class="blog-posts col-blog">
    @foreach (Blog_MVC.Models.Makale makale in Model)
    {
        <div class="post row">
            <div class="col-sm-4">
                <figure>
                    <a href="blog-post.html">
                        <div class="text-overlay">
                            <div class="info"><span>Devamını Oku</span></div>
                        </div>
                        <img src="style/images/art/b1.jpg" alt="" />
                    </a>
                </figure>
            </div>
            <div class="col-sm-8 post-content">
                <div class="meta"><span class="date">@makale.EklenmeTarihi.ToShortDateString()</span><span class="comments"><a href="#">@makale.Yorums.Count <i class="icon-chat-1"></i></a></span></div>
                <h2 class="post-title"><a href="blog-post.html">@makale.Baslik</a></h2>
                <p>
                    @IcerikKisalt(makale.Icerik)
                </p>
            </div>
        </div>
    }


</div>

Blog_MVC/Blog_MVC/Views/Home/PopulerMakalelerWidget.cshtml
@model IEnumerable<Blog_MVC.Models.Makale>

<div class="sidebox widget">
    <h3 class="widget-title section-title">Popular Posts</h3>
    <ul class="post-list">
        @foreach (Blog_MVC.Models.Makale makale in Model)
        {
            <li>
                <div class="icon-overlay"> <a href="blog-post.html"><img src="style/images/art/a1.jpg" alt="" /> </a> </div>
                <div class="meta">
                    <h5><a href="blog-post.html">@makale.Baslik</a></h5>
                    <em>@makale.EklenmeTarihi.ToShortDateString() <span class="comments"><a href="#">@makale.Yorums.Count <i class="icon-chat-1"></i></a></span></em>
                </div>
            </li>
        }
        
    </ul>
    <!-- /.post-list -->
</div>

Blog_MVC/Blog_MVC/Views/Home/SiteHakkinda.cshtml
<div class="sidebox widget">
    <h3 class="widget-title section-title">Hakkımda</h3>
    <p>Her türlü C# programlama işleri itina ile yapılır.</p>
    <ul class="social">
        <li><a href="#"><i class="icon-s-rss"></i></a></li>
        <li><a href="#"><i class="icon-s-twitter"></i></a></li>
        <li><a href="#"><i class="icon-s-facebook"></i></a></li>
        <li><a href="#"><i class="icon-s-pinterest"></i></a></li>
        <li><a href="#"><i class="icon-s-linkedin"></i></a></li>
        <li><a href="#"><i class="icon-s-dribbble"></i></a></li>
        <li><a href="#"><i class="icon-s-flickr"></i></a></li>
    </ul>
    <div class="clearfix"></div>
</div>